services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [MN\Gibmyx\Shared\Infrastructure\Doctrine\GibmyxEntityManagerFactory, create]
    arguments:
      - driver:   '%env(MOOC_DATABASE_DRIVER)%'
        host:     '%env(MOOC_DATABASE_HOST)%'
        port:     '%env(MOOC_DATABASE_PORT)%'
        dbname:   '%env(MOOC_DATABASE_NAME)%'
        user:     '%env(MOOC_DATABASE_USER)%'
        password: '%env(MOOC_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: mn.database_connection }
    public: true


  # Courses
  MN\Gibmyx\Courses\Domain\CourseRepository: '@MN\Gibmyx\Courses\Infrastructure\Persistence\DoctrineCourseRepository'